cassandra1:
  image: cassandra:latest
  container_name: cassandra1
  restart: always
  volumes:
    - "/data/cassandra/cassandra1:/var/lib/cassandra"
    - "/Users/ratchasak/Workspace/hospital/refrigensor/refrigensor_web/db:/home/docker"

cassandra2:
  image: cassandra:latest
  container_name: cassandra2
  links:
    - cassandra1:cassandra
  volumes:
    - "/data/cassandra/cassandra2:/var/lib/cassandra"